"""Domain enums shared across Phase 1 modules."""

from __future__ import annotations

from enum import StrEnum


class CaseStatus(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class EvidenceFormat(StrEnum):
    DIRECTORY = "DIRECTORY"
    RAW = "RAW"
    DD = "DD"
    IMG = "IMG"
    E01 = "E01"
    VHD = "VHD"
    VHDX = "VHDX"


class EvidenceStatus(StrEnum):
    REGISTERED = "REGISTERED"
    HASHING = "HASHING"
    READY = "READY"
    FAILED = "FAILED"


class HashAlgorithm(StrEnum):
    MD5 = "MD5"
    SHA1 = "SHA1"
    SHA256 = "SHA256"


class HashVerificationStatus(StrEnum):
    NOT_CHECKED = "NOT_CHECKED"
    MATCH = "MATCH"
    MISMATCH = "MISMATCH"
    ERROR = "ERROR"


class JobType(StrEnum):
    HASH = "HASH"
    VERIFY = "VERIFY"
    INDEX = "INDEX"
    ARTIFACT = "ARTIFACT"
    SEARCH_INDEX = "SEARCH_INDEX"
    TIMELINE = "TIMELINE"


class SchemaJobType(StrEnum):
    HASH = "HASH"
    VERIFY = "VERIFY"
    INDEX = "INDEX"
    ARTIFACT = "ARTIFACT"
    SEARCH_INDEX = "SEARCH_INDEX"
    TIMELINE = "TIMELINE"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    PAUSING = "PAUSING"
    PAUSED = "PAUSED"
    RESUMING = "RESUMING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ProgressUnit(StrEnum):
    BYTES = "BYTES"
    FILES = "FILES"
    TASKS = "TASKS"
    UNKNOWN = "UNKNOWN"


class FileSystemNodeType(StrEnum):
    ROOT = "ROOT"
    DIRECTORY = "DIRECTORY"
    FILE = "FILE"
    SYMLINK = "SYMLINK"
    REPARSE_POINT = "REPARSE_POINT"
    OTHER = "OTHER"


class FileSystemProviderCapability(StrEnum):
    LOGICAL_DIRECTORY = "LOGICAL_DIRECTORY"
    LOGICAL_FILE = "LOGICAL_FILE"
    METADATA_ONLY = "METADATA_ONLY"
    STABLE_RAW_LOCATOR = "STABLE_RAW_LOCATOR"


class IndexCoverageStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PARTIAL = "PARTIAL"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ArtifactType(StrEnum):
    REGISTRY_KEY = "REGISTRY_KEY"
    REGISTRY_VALUE = "REGISTRY_VALUE"
    REGISTRY_AUTORUN = "REGISTRY_AUTORUN"
    REGISTRY_USB_DEVICE = "REGISTRY_USB_DEVICE"
    REGISTRY_TIMEZONE = "REGISTRY_TIMEZONE"
    REGISTRY_USERASSIST = "REGISTRY_USERASSIST"
    EVENT_LOG_RECORD = "EVENT_LOG_RECORD"
    PREFETCH_EXECUTION = "PREFETCH_EXECUTION"
    MEDIA_IMAGE = "MEDIA_IMAGE"
    MEDIA_VIDEO = "MEDIA_VIDEO"
    MEDIA_AUDIO = "MEDIA_AUDIO"
    BROWSER_PROFILE = "BROWSER_PROFILE"
    BROWSER_VISIT = "BROWSER_VISIT"
    BROWSER_SEARCH = "BROWSER_SEARCH"
    BROWSER_DOWNLOAD = "BROWSER_DOWNLOAD"
    UNKNOWN_WINDOWS_ARTIFACT = "UNKNOWN_WINDOWS_ARTIFACT"


class ArtifactParseStatus(StrEnum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    UNSUPPORTED = "UNSUPPORTED"
    CORRUPT = "CORRUPT"
    FAILED = "FAILED"


class ArtifactSourceKind(StrEnum):
    REGISTRY_HIVE = "REGISTRY_HIVE"
    REGISTRY_EXPORT = "REGISTRY_EXPORT"
    EVENT_LOG_EVTX = "EVENT_LOG_EVTX"
    EVENT_LOG_XML = "EVENT_LOG_XML"
    PREFETCH_FILE = "PREFETCH_FILE"
    IMAGE_FILE = "IMAGE_FILE"
    VIDEO_FILE = "VIDEO_FILE"
    AUDIO_FILE = "AUDIO_FILE"
    BROWSER_SQLITE_DB = "BROWSER_SQLITE_DB"
    UNKNOWN_WINDOWS_ARTIFACT = "UNKNOWN_WINDOWS_ARTIFACT"


class ArtifactCoverageStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PARTIAL = "PARTIAL"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AnalysisProfileType(StrEnum):
    QUICK_TRIAGE = "QUICK_TRIAGE"
    SELECTED_SCOPE = "SELECTED_SCOPE"
    FULL_ANALYSIS = "FULL_ANALYSIS"
    CUSTOM = "CUSTOM"


class FollowLinkPolicy(StrEnum):
    NEVER = "NEVER"
    RECORD_ONLY = "RECORD_ONLY"


class CustodyEventType(StrEnum):
    ACQUISITION = "ACQUISITION"
    RECEIVED = "RECEIVED"
    TRANSFERRED = "TRANSFERRED"
    STORED = "STORED"
    OPENED = "OPENED"
    MOUNTED = "MOUNTED"
    ANALYZED = "ANALYZED"
    HASH_VERIFIED = "HASH_VERIFIED"
    COPIED = "COPIED"
    EXPORTED = "EXPORTED"
    RETURNED = "RETURNED"
    RELEASED = "RELEASED"
    ARCHIVED = "ARCHIVED"
    DISPOSED = "DISPOSED"
    CORRECTION = "CORRECTION"


class SearchSourceType(StrEnum):
    FILE_SYSTEM_NODE = "FILE_SYSTEM_NODE"
    WINDOWS_ARTIFACT = "WINDOWS_ARTIFACT"
    TIMELINE_EVENT = "TIMELINE_EVENT"


class SearchDocumentType(StrEnum):
    FILE = "FILE"
    DIRECTORY = "DIRECTORY"
    REGISTRY = "REGISTRY"
    EVENT_LOG = "EVENT_LOG"
    PREFETCH = "PREFETCH"
    MEDIA = "MEDIA"
    BROWSER = "BROWSER"
    TIMELINE = "TIMELINE"
    OTHER = "OTHER"


class SearchQueryMode(StrEnum):
    TERM = "TERM"
    PHRASE = "PHRASE"
    PREFIX = "PREFIX"
    EXACT = "EXACT"
    REGEX_METADATA = "REGEX_METADATA"


class KeywordSetStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class KeywordType(StrEnum):
    FILE_NAME = "FILE_NAME"
    PROCESS_NAME = "PROCESS_NAME"
    ACCOUNT = "ACCOUNT"
    EMAIL = "EMAIL"
    DOMAIN = "DOMAIN"
    URL = "URL"
    IP_ADDRESS = "IP_ADDRESS"
    REGISTRY_PATH = "REGISTRY_PATH"
    COMMAND = "COMMAND"
    PATH = "PATH"
    DOCUMENT_TERM = "DOCUMENT_TERM"
    HASH = "HASH"
    REGEX = "REGEX"
    RELATED_TERM = "RELATED_TERM"
    TRANSLITERATION = "TRANSLITERATION"
    TYPO_VARIANT = "TYPO_VARIANT"
    OTHER = "OTHER"


class KeywordMatchMode(StrEnum):
    TERM = "TERM"
    PHRASE = "PHRASE"
    PREFIX = "PREFIX"
    EXACT = "EXACT"
    REGEX_METADATA = "REGEX_METADATA"


class TimelineSourceType(StrEnum):
    FILE_SYSTEM_NODE = "FILE_SYSTEM_NODE"
    REGISTRY_ARTIFACT = "REGISTRY_ARTIFACT"
    EVENT_LOG_ARTIFACT = "EVENT_LOG_ARTIFACT"
    PREFETCH_ARTIFACT = "PREFETCH_ARTIFACT"
    MEDIA_ARTIFACT = "MEDIA_ARTIFACT"
    BROWSER_ARTIFACT = "BROWSER_ARTIFACT"
    ANALYST_ANNOTATION = "ANALYST_ANNOTATION"


class TimelineEventType(StrEnum):
    FILE_CREATED = "FILE_CREATED"
    FILE_MODIFIED = "FILE_MODIFIED"
    FILE_ACCESSED = "FILE_ACCESSED"
    FILE_METADATA_CHANGED = "FILE_METADATA_CHANGED"
    REGISTRY_KEY_LAST_WRITE = "REGISTRY_KEY_LAST_WRITE"
    REGISTRY_VALUE_OBSERVED = "REGISTRY_VALUE_OBSERVED"
    PROCESS_EXECUTION = "PROCESS_EXECUTION"
    LOGON = "LOGON"
    LOGOFF = "LOGOFF"
    PROCESS_CREATED = "PROCESS_CREATED"
    NETWORK_CONNECTION = "NETWORK_CONNECTION"
    FILE_CREATED_BY_PROCESS = "FILE_CREATED_BY_PROCESS"
    REGISTRY_MODIFIED = "REGISTRY_MODIFIED"
    DNS_QUERY = "DNS_QUERY"
    SERVICE_INSTALLED = "SERVICE_INSTALLED"
    EVENT_LOG_CLEARED = "EVENT_LOG_CLEARED"
    PREFETCH_LAST_RUN = "PREFETCH_LAST_RUN"
    MEDIA_CREATED = "MEDIA_CREATED"
    MEDIA_MODIFIED = "MEDIA_MODIFIED"
    MEDIA_CAPTURED = "MEDIA_CAPTURED"
    MEDIA_METADATA_TIMESTAMP = "MEDIA_METADATA_TIMESTAMP"
    MEDIA_CAPTURED_CANDIDATE = "MEDIA_CAPTURED_CANDIDATE"
    BROWSER_PROFILE_OBSERVED = "BROWSER_PROFILE_OBSERVED"
    BROWSER_VISIT = "BROWSER_VISIT"
    BROWSER_SEARCH = "BROWSER_SEARCH"
    BROWSER_DOWNLOAD = "BROWSER_DOWNLOAD"
    BROWSER_DOWNLOAD_STARTED = "BROWSER_DOWNLOAD_STARTED"
    BROWSER_DOWNLOAD_COMPLETED = "BROWSER_DOWNLOAD_COMPLETED"
    BROWSER_DOWNLOAD_OBSERVED = "BROWSER_DOWNLOAD_OBSERVED"
    OTHER = "OTHER"


class TimestampPrecision(StrEnum):
    SECOND = "SECOND"
    MILLISECOND = "MILLISECOND"
    MICROSECOND = "MICROSECOND"
    DAY = "DAY"
    UNKNOWN = "UNKNOWN"


class TimezoneSource(StrEnum):
    EXPLICIT_OFFSET = "EXPLICIT_OFFSET"
    UTC_SOURCE = "UTC_SOURCE"
    CASE_DEFAULT = "CASE_DEFAULT"
    ARTIFACT_CONFIGURATION = "ARTIFACT_CONFIGURATION"
    WINDOWS_TIMEZONE_CANDIDATE = "WINDOWS_TIMEZONE_CANDIDATE"
    ANALYST_CONFIRMED = "ANALYST_CONFIRMED"
    UNKNOWN = "UNKNOWN"


class TimezoneConfidence(StrEnum):
    CONFIRMED = "CONFIRMED"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class GuiRoute(StrEnum):
    CASE_OVERVIEW = "CASE_OVERVIEW"
    EVIDENCE = "EVIDENCE"
    FILE_SYSTEM = "FILE_SYSTEM"
    ARTIFACTS = "ARTIFACTS"
    REGISTRY = "REGISTRY"
    EVENT_LOG = "EVENT_LOG"
    PREFETCH = "PREFETCH"
    BROWSER = "BROWSER"
    MEDIA = "MEDIA"
    SEARCH = "SEARCH"
    TIMELINE = "TIMELINE"
    CANDIDATES = "CANDIDATES"
    CHAIN_OF_CUSTODY = "CHAIN_OF_CUSTODY"
    REPORT = "REPORT"
    SETTINGS = "SETTINGS"
    UNKNOWN = "UNKNOWN"


class AnalysisContextPurpose(StrEnum):
    AI_REQUEST = "AI_REQUEST"
    MCP_REQUEST = "MCP_REQUEST"
    REPORT_DRAFT = "REPORT_DRAFT"
    REPORT_REVIEW = "REPORT_REVIEW"
    ANALYST_BOOKMARK = "ANALYST_BOOKMARK"
    AUDIT = "AUDIT"
    EXPORT = "EXPORT"
    OTHER = "OTHER"


class AnalysisScopeType(StrEnum):
    CASE = "case"
    EVIDENCE = "evidence"
    FILESYSTEM = "filesystem"
    REGISTRY = "registry"
    EVENTLOG = "eventlog"
    PREFETCH = "prefetch"
    BROWSER = "browser"
    MEDIA = "media"
    TIMELINE = "timeline"
    KEYWORD_SEARCH = "keyword_search"
    MACHINE_CANDIDATE = "machine_candidate"
    CHAIN_OF_CUSTODY = "chain_of_custody"
    REPORT = "report"
    SELECTION = "selection"


class RevisionStatus(StrEnum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    MISSING = "MISSING"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"


class StaleReason(StrEnum):
    EVIDENCE_REVISION_CHANGED = "EVIDENCE_REVISION_CHANGED"
    FILESYSTEM_INDEX_CHANGED = "FILESYSTEM_INDEX_CHANGED"
    ARTIFACT_SOURCE_CHANGED = "ARTIFACT_SOURCE_CHANGED"
    SEARCH_INDEX_CHANGED = "SEARCH_INDEX_CHANGED"
    SEARCH_EXECUTION_STALE = "SEARCH_EXECUTION_STALE"
    TIMELINE_REVISION_CHANGED = "TIMELINE_REVISION_CHANGED"
    KEYWORD_SET_VERSION_CHANGED = "KEYWORD_SET_VERSION_CHANGED"
    CANDIDATE_REVIEW_CHANGED = "CANDIDATE_REVIEW_CHANGED"
    RESOURCE_MISSING = "RESOURCE_MISSING"
    PROVIDER_VERSION_CHANGED = "PROVIDER_VERSION_CHANGED"
    UNKNOWN = "UNKNOWN"


class ViewMode(StrEnum):
    SIMPLE = "SIMPLE"
    DETAILED = "DETAILED"
    RAW = "RAW"


class ResourceType(StrEnum):
    EVIDENCE = "EVIDENCE"
    FILE_SYSTEM_NODE = "FILE_SYSTEM_NODE"
    ARTIFACT = "ARTIFACT"
    REGISTRY = "REGISTRY"
    EVENT_LOG = "EVENT_LOG"
    PREFETCH = "PREFETCH"
    BROWSER = "BROWSER"
    MEDIA = "MEDIA"
    TIMELINE_EVENT = "TIMELINE_EVENT"
    SEARCH_RESULT = "SEARCH_RESULT"
    MACHINE_CANDIDATE = "MACHINE_CANDIDATE"
    CUSTODY_EVENT = "CUSTODY_EVENT"
    CONTEXT_SNAPSHOT = "CONTEXT_SNAPSHOT"
    OTHER = "OTHER"


class RawLocatorType(StrEnum):
    FILE_BYTE_RANGE = "FILE_BYTE_RANGE"
    FILE_LOGICAL_FIELD = "FILE_LOGICAL_FIELD"
    SQLITE_ROW = "SQLITE_ROW"
    SQLITE_TABLE_ROW_COLUMN = "SQLITE_TABLE_ROW_COLUMN"
    REGISTRY_KEY = "REGISTRY_KEY"
    REGISTRY_VALUE = "REGISTRY_VALUE"
    EVENT_RECORD = "EVENT_RECORD"
    PREFETCH_FIELD = "PREFETCH_FIELD"
    EXIF_TAG = "EXIF_TAG"
    MEDIA_METADATA_FIELD = "MEDIA_METADATA_FIELD"
    TIMELINE_SOURCE = "TIMELINE_SOURCE"
    SEARCH_DOCUMENT = "SEARCH_DOCUMENT"
    DERIVED_DATA = "DERIVED_DATA"
    UNKNOWN = "UNKNOWN"
