#!/usr/bin/env python3
"""Run advanced-runtime host verification probes without printing secret values."""

from __future__ import annotations

import argparse
import json
import os
import platform
import subprocess  # nosec B404
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

MAX_CAPTURE_CHARS = 20_000
_SECRET_ENV_FLAGS = {
    "--api-key-env",
    "--dpapi-password-env",
    "--dpapi-nt-hash-hex-env",
    "--dpapi-nt-hash-b64-env",
    "--dpapi-masterkey-hex-env",
    "--dpapi-masterkey-b64-env",
    "--dpapi-key-hex-env",
    "--dpapi-key-b64-env",
    "--nss-primary-password-env",
    "--password-env",
    "--nt-hash-hex-env",
    "--nt-hash-b64-env",
    "--masterkey-hex-env",
    "--masterkey-b64-env",
    "--key-hex-env",
    "--key-b64-env",
    "--primary-password-env",
    "--kakaotalk-pragma-key-env",
    "--kakaotalk-user-nonce-env",
    "--kakaotalk-db-key-hex-env",
    "--kakaotalk-db-iv-hex-env",
}

_EPILOG = """
Windows fixture policy:
  Use synthetic or legally redistributable fixtures only. Do not pass paths from the
  current user's live DPAPI, browser, Firefox, or KakaoTalk profile. Child verifiers
  reject known live profile roots before reading fixture contents.

PowerShell setup outside the repository:
  py -3.11 -m venv "$env:TEMP\\apex-advanced-runtime-venv"
  & "$env:TEMP\\apex-advanced-runtime-venv\\Scripts\\python.exe" -m pip install -e `
    ".[advanced-secrets,browser-media,machine-extraction,report-renderer]"

Synthetic fixture generation:
  & $py tools\\generate_windows_runtime_fixtures.py `
    --output-dir "$env:TEMP\\apex-fixtures" `
    --manifest-path "$env:TEMP\\apex-fixtures\\manifest.json" `
    --require-all `
    --json

Linux-generated NSS fixtures:
  Generate the synthetic NSS fixture on a Linux host with libnss3, copy the complete
  fixture directory to Windows, then pass the copied manifest to --fixture-manifest.
  Manifest-relative paths are preferred over the original generation host paths.

PowerShell one-shot runner:
  .\\tools\\run_windows_runtime_verification.ps1 -Python $py

PowerShell DPAPI/NSS host smoke:
  $py = "$env:TEMP\\apex-advanced-runtime-venv\\Scripts\\python.exe"
  $env:APEX_DPAPI_FIXTURE_PASSWORD = "<synthetic-fixture-password>"
  $env:APEX_NSS_PRIMARY_PASSWORD = "<synthetic-fixture-primary-password>"
  & $py tools\\verify_windows_host_runtime.py `
    --python $py `
    --dpapi-input-file C:\\apex-fixtures\\dpapi\\blob.bin `
    --dpapi-local-state-path "C:\\apex-fixtures\\dpapi\\Local State" `
    --dpapi-decrypt-local-state-key `
    --dpapi-sid S-1-5-21-1111111111-2222222222-3333333333-1001 `
    --dpapi-masterkey-path C:\\apex-fixtures\\dpapi\\Protect\\masterkey.bin `
    --dpapi-password-env APEX_DPAPI_FIXTURE_PASSWORD `
    --nss-root-path C:\\apex-fixtures\\firefox `
    --nss-profile-path C:\\apex-fixtures\\firefox\\Profiles\\verify.default `
    --nss-primary-password-env APEX_NSS_PRIMARY_PASSWORD

DPAPI fixture manifest fields:
  fixture_id, source, license, sid, masterkey_path, input_file, local_state_path,
  algorithm, expected_plaintext_sha256, expected_key_source, version.

NSS fixture manifest fields:
  fixture_id, source, license, profile_path, key4_db_path, logins_json_path,
  primary_password_required, expected_login_count, expected_plaintext_sha256, version.
"""


@dataclass(frozen=True, slots=True)
class Probe:
    name: str
    command: list[str]
    requires_windows: bool = False
    requires_secret: bool = False
    fixture_configured: bool = True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify advanced APEX runtimes on a Windows forensic host.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=_EPILOG,
    )
    parser.add_argument("--python", default=sys.executable)
    parser.add_argument("--timeout", type=float, default=120.0)
    parser.add_argument(
        "--fixture-manifest",
        help="Synthetic fixture manifest generated by generate_windows_runtime_fixtures.py.",
    )
    parser.add_argument(
        "--skip-execution",
        action="store_true",
        help="Only print the host/probe matrix; do not execute verifier scripts.",
    )
    parser.add_argument(
        "--exclude-probe",
        action="append",
        default=[],
        metavar="NAME",
        help="Exclude a named probe and report the exclusion explicitly.",
    )
    parser.add_argument("--dpapi-input-file")
    parser.add_argument("--dpapi-local-state-path")
    parser.add_argument("--dpapi-decrypt-local-state-key", action="store_true")
    parser.add_argument("--dpapi-chromium-input-file")
    parser.add_argument("--dpapi-sid")
    parser.add_argument("--dpapi-masterkey-path")
    parser.add_argument("--dpapi-password-env")
    parser.add_argument("--dpapi-nt-hash-hex-env")
    parser.add_argument("--dpapi-nt-hash-b64-env")
    parser.add_argument("--dpapi-masterkey-hex-env")
    parser.add_argument("--dpapi-masterkey-b64-env")
    parser.add_argument("--dpapi-key-hex-env")
    parser.add_argument("--dpapi-key-b64-env")
    parser.add_argument("--nss-root-path")
    parser.add_argument("--nss-profile-path")
    parser.add_argument("--nss-primary-password-env")
    parser.add_argument("--kakaotalk-store-path")
    parser.add_argument("--kakaotalk-profile-root")
    parser.add_argument("--kakaotalk-pragma-key-env")
    parser.add_argument("--kakaotalk-user-nonce-env")
    parser.add_argument("--kakaotalk-db-key-hex-env")
    parser.add_argument("--kakaotalk-db-iv-hex-env")
    args = parser.parse_args()
    if args.fixture_manifest:
        try:
            _apply_fixture_manifest(args, Path(args.fixture_manifest))
        except (OSError, TypeError, ValueError, json.JSONDecodeError) as error:
            parser.error(f"invalid fixture manifest: {error}")

    root = Path(__file__).resolve().parents[1]
    is_windows = platform.system().casefold() == "windows"
    probes = _probes(root, args.python, args)

    results: list[dict[str, Any]] = []
    for probe in probes:
        if probe.name in args.exclude_probe:
            results.append(
                _skipped_probe(
                    probe,
                    "SKIPPED_WITH_REASON",
                    reason="EXCLUDED_BY_REQUEST",
                )
            )
            continue
        if args.skip_execution:
            results.append(_skipped_probe(probe, "SKIPPED_BY_REQUEST"))
            continue
        if probe.requires_windows and not is_windows:
            results.append(_skipped_probe(probe, "HOST_VERIFICATION_REQUIRED"))
            continue
        if not probe.fixture_configured:
            results.append(_skipped_probe(probe, "EXTERNAL_FIXTURE_NOT_CONFIGURED"))
            continue
        if probe.requires_secret and not _ai_env_ready():
            results.append(_skipped_probe(probe, "EXTERNAL_PROVIDER_NOT_CONFIGURED"))
            continue
        results.append(_run_probe(probe, timeout=args.timeout, cwd=root))

    payload = {
        "host_platform": platform.platform(),
        "host_platform_status": "WINDOWS" if is_windows else "HOST_VERIFICATION_REQUIRED",
        "python": args.python,
        "secret_values_emitted": False,  # nosec
        "windows_runtime_success_claimed": is_windows
        and all(_probe_passed(results, name) for name in ("dpapi", "nss")),
        "windows_host_dpapi_nss_verified": is_windows
        and all(_probe_passed(results, name) for name in ("dpapi", "nss")),
        "probes": results,
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 1 if any(item["status"] == "FAILED" for item in results) else 0


def _probes(root: Path, python_executable: str, args: argparse.Namespace) -> list[Probe]:
    def script(name: str) -> str:
        return str(root / "tools" / name)

    dpapi_command = [python_executable, script("verify_dpapi_runtime.py")]
    _append_option(dpapi_command, "--input-file", args.dpapi_input_file)
    _append_option(dpapi_command, "--local-state-path", args.dpapi_local_state_path)
    if args.dpapi_decrypt_local_state_key:
        dpapi_command.append("--decrypt-local-state-key")
    _append_option(dpapi_command, "--chromium-input-file", args.dpapi_chromium_input_file)
    _append_option(dpapi_command, "--sid", args.dpapi_sid)
    _append_option(dpapi_command, "--masterkey-path", args.dpapi_masterkey_path)
    _append_option(dpapi_command, "--password-env", args.dpapi_password_env)
    _append_option(dpapi_command, "--nt-hash-hex-env", args.dpapi_nt_hash_hex_env)
    _append_option(dpapi_command, "--nt-hash-b64-env", args.dpapi_nt_hash_b64_env)
    _append_option(dpapi_command, "--masterkey-hex-env", args.dpapi_masterkey_hex_env)
    _append_option(dpapi_command, "--masterkey-b64-env", args.dpapi_masterkey_b64_env)
    _append_option(dpapi_command, "--key-hex-env", args.dpapi_key_hex_env)
    _append_option(dpapi_command, "--key-b64-env", args.dpapi_key_b64_env)
    dpapi_command.append("--require-available")

    nss_command = [python_executable, script("verify_nss_runtime.py")]
    _append_option(nss_command, "--root-path", args.nss_root_path)
    _append_option(nss_command, "--profile-path", args.nss_profile_path)
    _append_option(nss_command, "--primary-password-env", args.nss_primary_password_env)
    nss_command.append("--require-available")

    kakaotalk_command = [python_executable, script("verify_kakaotalk_runtime.py")]
    _append_option(kakaotalk_command, "--store-path", args.kakaotalk_store_path)
    _append_option(kakaotalk_command, "--profile-root", args.kakaotalk_profile_root)
    _append_option(kakaotalk_command, "--pragma-key-env", args.kakaotalk_pragma_key_env)
    _append_option(kakaotalk_command, "--user-nonce-env", args.kakaotalk_user_nonce_env)
    _append_option(kakaotalk_command, "--db-key-hex-env", args.kakaotalk_db_key_hex_env)
    _append_option(kakaotalk_command, "--db-iv-hex-env", args.kakaotalk_db_iv_hex_env)

    probes = [
        Probe(
            "dpapi",
            dpapi_command,
            requires_windows=True,
            fixture_configured=_dpapi_fixture_configured(args),
        ),
        Probe(
            "nss",
            nss_command,
            requires_windows=True,
            fixture_configured=_nss_fixture_configured(args),
        ),
        Probe("kakaotalk", kakaotalk_command),
        Probe("ocr", [python_executable, script("verify_ocr_runtime.py")]),
        Probe("stt", [python_executable, script("verify_stt_runtime.py")]),
        Probe(
            "report-renderers",
            [python_executable, script("verify_report_renderers.py"), "--require-pdf"],
        ),
        Probe(
            "windows-event-message-renderer",
            [python_executable, script("verify_windows_event_message_renderer.py")],
            requires_windows=True,
        ),
    ]
    ai_command = [
        python_executable,
        script("verify_ai_provider.py"),
        "--base-url",
        os.environ.get("APEX_AI_VERIFY_BASE_URL", ""),
        "--model",
        os.environ.get("APEX_AI_VERIFY_MODEL", ""),
        "--api-key-env",
        os.environ.get("APEX_AI_VERIFY_API_KEY_ENV", ""),
        "--operation",
        os.environ.get("APEX_AI_VERIFY_OPERATION", "capability"),
    ]
    probes.append(Probe("ai-provider", ai_command, requires_secret=True))
    return probes


def _append_option(command: list[str], flag: str, value: str | None) -> None:
    if value:
        command.extend([flag, value])


def _dpapi_fixture_configured(args: argparse.Namespace) -> bool:
    return bool(
        args.dpapi_input_file
        or args.dpapi_local_state_path
        or args.dpapi_chromium_input_file
        or args.dpapi_masterkey_path
    )


def _nss_fixture_configured(args: argparse.Namespace) -> bool:
    return bool(args.nss_root_path or args.nss_profile_path)


def _apply_fixture_manifest(args: argparse.Namespace, manifest_path: Path) -> None:
    base = manifest_path.expanduser().resolve(strict=False).parent
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(manifest, dict):
        raise ValueError("manifest root must be an object")
    dpapi = manifest.get("dpapi")
    if isinstance(dpapi, dict) and dpapi.get("status") == "GENERATED":
        _set_default(args, "dpapi_input_file", _manifest_fixture_path(dpapi, "input_file", base))
        _set_default(
            args,
            "dpapi_local_state_path",
            _manifest_fixture_path(dpapi, "local_state_path", base),
        )
        _set_default(
            args,
            "dpapi_chromium_input_file",
            _manifest_fixture_path(dpapi, "chromium_input_file", base),
        )
        _set_default(args, "dpapi_sid", _string_or_none(dpapi.get("sid")))
        _set_default(
            args,
            "dpapi_masterkey_path",
            _manifest_fixture_path(dpapi, "masterkey_path", base),
        )
        _set_default(args, "dpapi_password_env", _string_or_none(dpapi.get("credential_env")))
        args.dpapi_decrypt_local_state_key = True
    nss = manifest.get("nss")
    if isinstance(nss, dict) and nss.get("status") == "GENERATED":
        _set_default(args, "nss_root_path", _manifest_fixture_path(nss, "root_path", base))
        _set_default(args, "nss_profile_path", _manifest_fixture_path(nss, "profile_path", base))
        _set_default(
            args,
            "nss_primary_password_env",
            _string_or_none(nss.get("primary_password_env")),
        )


def _set_default(args: argparse.Namespace, attr: str, value: str | None) -> None:
    if value and not getattr(args, attr):
        setattr(args, attr, value)


def _manifest_fixture_path(section: dict[str, Any], key: str, base: Path) -> str | None:
    return _manifest_path(section.get(f"{key}_relative"), base) or _manifest_path(
        section.get(key),
        base,
    )


def _manifest_path(value: object, base: Path) -> str | None:
    text = _string_or_none(value)
    if text is None:
        return None

    normalized = text.replace("\\", "/")
    lowered = normalized.casefold()

    relative_text: str | None = None
    for prefix in ("/fixtures/", "c:/fixtures/"):
        if lowered.startswith(prefix):
            relative_text = normalized[len(prefix):]
            break

    if relative_text is not None:
        fixture_root = base.resolve(strict=False)
        candidate = (fixture_root / Path(relative_text)).resolve(strict=False)
        try:
            candidate.relative_to(fixture_root)
        except ValueError as error:
            raise ValueError(
                "fixture manifest path escapes fixture root"
            ) from error
        return str(candidate)

    path = Path(text)
    if not path.is_absolute():
        path = base / path
    return str(path.resolve(strict=False))


def _string_or_none(value: object) -> str | None:
    return value if isinstance(value, str) and value else None


def _ai_env_ready() -> bool:
    key_env = os.environ.get("APEX_AI_VERIFY_API_KEY_ENV")
    return bool(
        os.environ.get("APEX_AI_VERIFY_BASE_URL")
        and os.environ.get("APEX_AI_VERIFY_MODEL")
        and key_env
        and os.environ.get(key_env)
    )


def _probe_passed(results: list[dict[str, Any]], name: str) -> bool:
    return any(item["name"] == name and item["status"] == "PASSED" for item in results)


def _skipped_probe(
    probe: Probe,
    status: str,
    *,
    reason: str | None = None,
) -> dict[str, Any]:
    result = {
        "name": probe.name,
        "status": status,
        "command": _redacted_command(probe.command),
        "returncode": None,
        "stdout": "",
        "stderr": "",
    }
    if reason is not None:
        result["reason"] = reason
    return result


def _run_probe(probe: Probe, *, timeout: float, cwd: Path) -> dict[str, Any]:
    env_names = _secret_env_names_from_command(probe.command)
    try:
        completed = subprocess.run(  # nosec B603
            probe.command,
            cwd=cwd,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as error:
        return {
            "name": probe.name,
            "status": "FAILED",
            "command": _redacted_command(probe.command),
            "returncode": None,
            "stdout": _redact_env_names_in_text(_truncate(error.stdout), env_names),
            "stderr": _redact_env_names_in_text(_truncate(error.stderr), env_names),
            "error_code": "TIMEOUT",
        }
    child_json, json_error = _parse_child_json(completed.stdout)
    if child_json is not None:
        child_json = _redact_env_names_in_json(child_json, env_names)
    status, semantic_checks = _classify_probe_status(
        probe.name,
        returncode=completed.returncode,
        child_json=child_json,
        json_error=json_error,
    )
    result: dict[str, Any] = {
        "name": probe.name,
        "status": status,
        "command": _redacted_command(probe.command),
        "returncode": completed.returncode,
        "stdout": _redact_env_names_in_text(_truncate(completed.stdout), env_names),
        "stderr": _redact_env_names_in_text(_truncate(completed.stderr), env_names),
        "semantic_checks": semantic_checks,
    }
    if child_json is not None:
        result["child_json"] = child_json
    if json_error is not None:
        result["json_parse_error"] = json_error
    return result


def _parse_child_json(stdout: str) -> tuple[dict[str, Any] | None, str | None]:
    try:
        parsed = json.loads(stdout)
    except json.JSONDecodeError as error:
        return None, f"{error.msg} at line {error.lineno} column {error.colno}"
    if not isinstance(parsed, dict):
        return None, "child JSON stdout root must be an object"
    return parsed, None


def _classify_probe_status(
    name: str,
    *,
    returncode: int,
    child_json: dict[str, Any] | None,
    json_error: str | None,
) -> tuple[str, dict[str, Any]]:
    if child_json is None:
        return "FAILED", {
            "json_stdout_parsed": False,
            "json_error": json_error or "missing child JSON stdout",
        }
    if name == "dpapi":
        status, checks = _classify_dpapi_probe(child_json)
    elif name == "nss":
        status, checks = _classify_nss_probe(child_json)
    elif name == "report-renderers":
        status, checks = _classify_report_renderer_probe(child_json)
    elif name == "windows-event-message-renderer":
        status, checks = _classify_windows_event_message_probe(child_json)
    elif name == "ocr":
        status, checks = _classify_ocr_probe(child_json)
    elif name == "stt":
        status, checks = _classify_stt_probe(child_json)
    elif name == "kakaotalk":
        status, checks = _classify_kakaotalk_probe(child_json)
    elif name == "ai-provider":
        status, checks = _classify_ai_provider_probe(child_json)
    else:
        status = "PASSED" if returncode == 0 else "FAILED"
        checks = {"returncode_zero": returncode == 0}
    if status == "PASSED" and returncode != 0:
        checks = checks | {"returncode_zero": False}
        return "FAILED", {"json_stdout_parsed": True} | checks
    return status, {"json_stdout_parsed": True} | checks


def _classify_dpapi_probe(payload: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    runtime_status = _nested_str(payload, "capability", "runtime_status")
    decrypt_status = _nested_str(payload, "decrypt", "status")
    local_state_status = _nested_str(payload, "local_state_decrypt", "status")
    chromium_status = _nested_str(payload, "chromium_decrypt", "status")
    emitted_violations = _emitted_value_violations(payload)
    checks = {
        "runtime_status": runtime_status,
        "decrypt_status": decrypt_status,
        "local_state_decrypt_status": local_state_status,
        "chromium_decrypt_status": chromium_status,
        "emitted_value_violations": emitted_violations,
    }
    if (
        runtime_status == "IMPLEMENTED_RUNTIME"
        and decrypt_status == "DECRYPTED"
        and local_state_status == "DECRYPTED"
        and chromium_status == "DECRYPTED"
        and not emitted_violations
    ):
        return "PASSED", checks
    failure_statuses = [
        status
        for status in (runtime_status, decrypt_status, local_state_status, chromium_status)
        if status and status != "DECRYPTED" and status != "IMPLEMENTED_RUNTIME"
    ]
    checks = checks | {"failure_statuses": failure_statuses}
    if runtime_status == "CAPABILITY_UNAVAILABLE" or "CAPABILITY_UNAVAILABLE" in failure_statuses:
        return "CAPABILITY_UNAVAILABLE", checks
    return "FAILED", checks


def _classify_nss_probe(payload: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    runtime_status = _nested_str(payload, "capability", "runtime_status")
    decrypt = payload.get("decrypt")
    decrypt_items = decrypt if isinstance(decrypt, list) else []
    decrypt_statuses = [
        str(item.get("status"))
        for item in decrypt_items
        if isinstance(item, dict) and item.get("status") is not None
    ]
    secret_field_violations = _flag_violations(payload, names={"secret_fields_emitted"})
    plaintext_violations = _plaintext_field_violations(payload)
    checks = {
        "runtime_status": runtime_status,
        "decrypt_count": len(decrypt_items),
        "decrypt_statuses": decrypt_statuses,
        "secret_field_violations": secret_field_violations,
        "plaintext_field_violations": plaintext_violations,
    }
    if (
        runtime_status == "IMPLEMENTED_RUNTIME"
        and decrypt_items
        and decrypt_statuses
        and len(decrypt_statuses) == len(decrypt_items)
        and all(status == "NSS_DECRYPTED" for status in decrypt_statuses)
        and not secret_field_violations
        and not plaintext_violations
    ):
        return "PASSED", checks
    if runtime_status == "CAPABILITY_UNAVAILABLE" or any(
        status in {"CAPABILITY_UNAVAILABLE", "NSS_CAPABILITY_UNAVAILABLE"}
        for status in decrypt_statuses
    ):
        return "CAPABILITY_UNAVAILABLE", checks
    return "FAILED", checks


def _classify_report_renderer_probe(payload: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    html_status = _nested_str(payload, "html", "status")
    pdf_status = _nested_str(payload, "pdf", "status")
    checks = {
        "html_status": html_status,
        "pdf_status": pdf_status,
    }
    if html_status == "COMPLETED" and pdf_status == "COMPLETED":
        return "PASSED", checks
    return "FAILED", checks


def _classify_windows_event_message_probe(
    payload: dict[str, Any],
) -> tuple[str, dict[str, Any]]:
    rendered = payload.get("message_rendered") is True
    status = _nested_str(payload, "message_rendering", "status")
    rendered_message = payload.get("rendered_message")
    checks = {
        "message_rendered": rendered,
        "message_rendering_status": status,
        "rendered_message_present": isinstance(rendered_message, str) and bool(rendered_message),
    }
    if (
        rendered
        and checks["rendered_message_present"]
        and status in {"RENDERED", "WINDOWS_ADAPTER_RENDERED"}
    ):
        return "PASSED", checks
    if status in {"WINDOWS_HOST_REQUIRED", "HOST_VERIFICATION_REQUIRED"}:
        return "HOST_VERIFICATION_REQUIRED", checks
    if status == "PYWIN32_UNAVAILABLE":
        return "CAPABILITY_UNAVAILABLE", checks
    return "FAILED", checks


def _classify_ocr_probe(payload: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    analysis = payload.get("analysis")
    analysis_status = _nested_str(payload, "analysis", "status")
    is_available = payload.get("is_available") is True
    unavailable_reason = str(payload.get("unavailable_reason") or "CAPABILITY_UNAVAILABLE")
    candidate_count = _nested_int(payload, "analysis", "candidate_count")
    required_candidate_present = _nested_bool(payload, "analysis", "required_candidate_present")
    expected_text_present = _nested_bool(payload, "analysis", "expected_text_present")
    checks = {
        "is_available": is_available,
        "unavailable_reason": None if is_available else unavailable_reason,
        "analysis_status": analysis_status,
        "candidate_count": candidate_count,
        "required_candidate_present": required_candidate_present,
        "expected_text_present": expected_text_present,
    }
    if not is_available:
        return unavailable_reason, checks
    if not isinstance(analysis, dict):
        return "NOT_CONFIGURED", checks
    if (
        analysis_status == "COMPLETED"
        and candidate_count is not None
        and candidate_count > 0
        and required_candidate_present is not False
        and expected_text_present is not False
    ):
        return "PASSED", checks
    if analysis_status in {"CAPABILITY_UNAVAILABLE", "NOT_CONFIGURED"}:
        return str(analysis_status), checks
    return "FAILED", checks


def _classify_stt_probe(payload: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    capability = payload.get("capability") if isinstance(payload.get("capability"), dict) else {}
    verification = (
        payload.get("verification") if isinstance(payload.get("verification"), dict) else {}
    )
    segments = payload.get("segments")
    is_available = capability.get("is_available") is True
    unavailable_reason = str(capability.get("unavailable_reason") or "CAPABILITY_UNAVAILABLE")
    audio_path_supplied = verification.get("audio_path_supplied") is True
    required_segment_present = verification.get("required_segment_present")
    expected_text_present = verification.get("expected_text_present")
    segment_count = verification.get("segment_count")
    analysis_error = payload.get("analysis_error")
    checks = {
        "is_available": is_available,
        "unavailable_reason": None if is_available else unavailable_reason,
        "audio_path_supplied": audio_path_supplied,
        "segment_count": segment_count if isinstance(segment_count, int) else None,
        "required_segment_present": required_segment_present
        if isinstance(required_segment_present, bool)
        else None,
        "expected_text_present": expected_text_present
        if isinstance(expected_text_present, bool)
        else None,
    }
    if not is_available:
        return unavailable_reason, checks
    if not audio_path_supplied:
        return "NOT_CONFIGURED", checks
    if isinstance(analysis_error, dict):
        return str(analysis_error.get("code") or "FAILED"), checks
    if (
        isinstance(segments, list)
        and segments
        and required_segment_present is not False
        and expected_text_present is not False
    ):
        return "PASSED", checks
    return "FAILED", checks


def _classify_kakaotalk_probe(payload: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    key_acquisition_status = _nested_str(payload, "key_acquisition", "status")
    decrypt_status = _nested_str(payload, "decrypt", "status")
    decrypt_partial = _nested_bool(payload, "decrypt", "partial")
    real_fixture_verified = _nested_bool(
        payload,
        "verification",
        "real_kakaotalk_fixture_verified",
    )
    external_key_decrypted = _nested_bool(
        payload,
        "verification",
        "external_key_contract_decrypted",
    )
    emitted_violations = _emitted_value_violations(payload)
    checks = {
        "key_acquisition_status": key_acquisition_status,
        "decrypt_status": decrypt_status,
        "decrypt_partial": decrypt_partial,
        "real_kakaotalk_fixture_verified": real_fixture_verified,
        "external_key_contract_decrypted": external_key_decrypted,
        "emitted_value_violations": emitted_violations,
    }
    if (
        decrypt_status == "KAKAOTALK_DECRYPTED"
        and decrypt_partial is not True
        and real_fixture_verified is True
        and external_key_decrypted is True
        and not emitted_violations
    ):
        return "PASSED", checks
    if decrypt_status == "PARTIAL" or decrypt_partial is True:
        return "PARTIAL", checks
    if key_acquisition_status == "BLOCKED_EXTERNAL_FIXTURE" or real_fixture_verified is not True:
        return "BLOCKED_EXTERNAL_FIXTURE", checks
    return decrypt_status or "FAILED", checks


def _classify_ai_provider_probe(payload: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    verification_status = payload.get("verification_status")
    capability = payload.get("capability") if isinstance(payload.get("capability"), dict) else {}
    execution = payload.get("execution") if isinstance(payload.get("execution"), dict) else {}
    is_available = capability.get("is_available") is True
    unavailable_reason = capability.get("unavailable_reason")
    execution_status = execution.get("status")
    safe_verification_status = (
        verification_status if isinstance(verification_status, str) else None
    )
    checks = {
        "verification_status": safe_verification_status,
        "is_available": is_available,
        "unavailable_reason": unavailable_reason if isinstance(unavailable_reason, str) else None,
        "execution_status": execution_status if isinstance(execution_status, str) else None,
    }
    if verification_status == "EXTERNAL_PROVIDER_NOT_CONFIGURED":
        return "EXTERNAL_PROVIDER_NOT_CONFIGURED", checks
    if not is_available:
        return str(unavailable_reason or verification_status or "CAPABILITY_UNAVAILABLE"), checks
    if execution_status:
        return ("PASSED" if execution_status == "COMPLETED" else str(execution_status)), checks
    return "PASSED", checks


def _nested_str(payload: dict[str, Any], *path: str) -> str | None:
    value = _nested_value(payload, *path)
    return value if isinstance(value, str) else None


def _nested_int(payload: dict[str, Any], *path: str) -> int | None:
    value = _nested_value(payload, *path)
    return value if isinstance(value, int) else None


def _nested_bool(payload: dict[str, Any], *path: str) -> bool | None:
    value = _nested_value(payload, *path)
    return value if isinstance(value, bool) else None


def _nested_value(payload: dict[str, Any], *path: str) -> Any:
    value: Any = payload
    for key in path:
        if not isinstance(value, dict):
            return None
        value = value.get(key)
    return value


def _emitted_value_violations(payload: Any) -> list[str]:
    return _flag_violations(payload, suffix="_emitted") + _plaintext_field_violations(payload)


def _flag_violations(
    payload: Any,
    *,
    names: set[str] | None = None,
    suffix: str | None = None,
) -> list[str]:
    violations: list[str] = []

    def visit(value: Any, path: str) -> None:
        if isinstance(value, dict):
            for key, item in value.items():
                key_text = str(key)
                child_path = f"{path}.{key_text}" if path else key_text
                is_tracked_flag = (names is not None and key_text in names) or (
                    suffix is not None and key_text.endswith(suffix)
                )
                if is_tracked_flag and not (
                    item is False or item == "<redacted>"
                ):
                    violations.append(child_path)
                visit(item, child_path)
        elif isinstance(value, list):
            for index, item in enumerate(value):
                visit(item, f"{path}[{index}]")

    visit(payload, "")
    return violations


def _plaintext_field_violations(payload: Any) -> list[str]:
    violations: list[str] = []

    def visit(value: Any, path: str) -> None:
        if isinstance(value, dict):
            for key, item in value.items():
                key_text = str(key)
                child_path = f"{path}.{key_text}" if path else key_text
                if key_text in {"plaintext_b64", "secret_b64"}:
                    violations.append(child_path)
                visit(item, child_path)
        elif isinstance(value, list):
            for index, item in enumerate(value):
                visit(item, f"{path}[{index}]")

    visit(payload, "")
    return violations


def _redacted_command(command: list[str]) -> list[str]:
    redacted: list[str] = []
    redact_next = False
    for item in command:
        if redact_next:
            redacted.append("<env-name>")
            redact_next = False
            continue
        redacted.append(item)
        if item in _SECRET_ENV_FLAGS:
            redact_next = True
    return redacted


def _secret_env_names_from_command(command: list[str]) -> set[str]:
    env_names: set[str] = set()
    capture_next = False
    for item in command:
        if capture_next:
            if item:
                env_names.add(item)
            capture_next = False
            continue
        if item in _SECRET_ENV_FLAGS:
            capture_next = True
    return env_names


def _redact_env_names_in_text(text: str, env_names: set[str]) -> str:
    redacted = text
    for env_name in sorted(env_names, key=len, reverse=True):
        redacted = redacted.replace(env_name, "<env-name>")
    return redacted


def _redact_env_names_in_json(value: Any, env_names: set[str]) -> Any:
    if isinstance(value, str):
        return _redact_env_names_in_text(value, env_names)
    if isinstance(value, dict):
        return {
            str(key): _redact_env_names_in_json(item, env_names) for key, item in value.items()
        }
    if isinstance(value, list):
        return [_redact_env_names_in_json(item, env_names) for item in value]
    return value


def _truncate(value: str | bytes | None) -> str:
    if value is None:
        return ""
    text = value.decode("utf-8", errors="replace") if isinstance(value, bytes) else value
    if len(text) <= MAX_CAPTURE_CHARS:
        return text
    return text[:MAX_CAPTURE_CHARS] + "...<truncated>"


if __name__ == "__main__":
    raise SystemExit(main())
